{
 "title": "Reblaze 5.0 Threats Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "description": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font size= \"10\"> <center>  Reblaze threats overview  </center></font> "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic Peak ",
   "type": "table",
   "description": "total number of requests  ",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "targets": [
    { "expr": "(sum(irate(hits_total[30s])))", "legendFormat": "Hits" }
   ]
  },
  {
   "title": "Hits",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(irate(hits_total[30s])) " }
   ]
  },
  {
   "title": "Passed",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(passed_total[30s])))"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(hits_total[30s])) -  sum(irate(passed_total[30s])))"
    }
   ]
  },
  {
   "title": "Report",
   "type": "stat",
   "description": "total number of requests  labeled as report ",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(reported_total[30s])))"
    }
   ]
  },
  {
   "title": "bot",
   "type": "stat",
   "description": "total number of requests  labeled as bot ",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(irate(hits_total[30s]))" }
   ]
  },
  {
   "title": "Human",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(irate(human_total[30s]))" }
   ]
  },
  {
   "title": "Challenge",
   "type": "stat",
   "description": "total number of requests  labeled as human ",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(irate(challenge_total[30s]))"
    }
   ]
  },
  {
   "title": "Traffic overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(irate(hits_total[30s]))", "legendFormat": "hits" },
    {
     "expr": "sum(irate(hits_total[30s])) - sum(irate(passed_total[30s]))",
     "legendFormat": "blocked"
    },
    { "expr": "sum(irate(passed_total[30s]))", "legendFormat": "passed" },
    {
     "expr": "sum(irate(reported_total[30s]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Traffic overview (ratio)",
   "type": "graph",
   "description": "Ratio of blocked,  passed, reported requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(hits_total[30s])) - sum(irate(passed_total[30s])))",
     "legendFormat": "blocked"
    },
    {
     "expr": "round(sum(irate(passed_total[30s])))",
     "legendFormat": "passed"
    },
    {
     "expr": "round(sum(irate(reported_total[30s])))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (method) (irate(methods_total[10s]))",
     "legendFormat": "{{method}}"
    },
    {}
   ]
  },
  {
   "title": "Statuses",
   "type": "timeseries",
   "description": "total number of requests  grouped by http statuses",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (code) (irate(status_total[10s])) ",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (tag) (irate(top_tags_reported_total[10s]))) ",
     "legendFormat": "report: {{tag}}"
    },
    {
     "expr": "round(sum by (tag) (irate(top_tags_active_total[10s]))) ",
     "legendFormat": "active:{{tag}}"
    }
   ]
  },
  {
   "title": "Unique Arguments per request",
   "type": "graph",
   "description": "Number of  requests  per  unique  args  divided  into categories  (from 0 to 5, 6-10, 11-20,  greater then 21)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " round(sum by (group) (irate(top_max_args_per_request[10s]))) ",
     "legendFormat": "args:{{group}}"
    }
   ]
  },
  {
   "title": "Unique Headers per request",
   "type": "graph",
   "description": "Number of  requests  per  unique  Headers  divided  into categories  (from 0 to 5, 6-10, 11-20,  greater then 21)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (group) (irate(top_max_headers_per_request[10s]))) ",
     "legendFormat": "headers:{{group}}"
    }
   ]
  },
  {
   "title": "Unique Cookies per request",
   "type": "graph",
   "description": "Number of  requests  per  unique  Cookies  divided  into categories  (from 0 to 5, 6-10, 11-20,  greater then 21)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (group) (irate(top_max_cookies_per_request[10s]))) ",
     "legendFormat": "cookies:{{group}}"
    }
   ]
  },
  {
   "title": "Global Filter",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(irate(requests_triggered_globalfilter_active_total[30s]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(irate(requests_triggered_globalfilter_report_total[30s]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Rate Limit",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(irate(requests_triggered_ratelimit_active_total[30s]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(irate(requests_triggered_ratelimit_report_total[30s]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "ACL",
   "type": "stat",
   "description": "total number of requests  labeled  with ruleid ",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(irate(requests_triggered_acl_active_total[30s]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(irate(requests_triggered_acl_report_total[30s]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Risk Level ",
   "type": "gauge",
   "description": "number of requests grouped by risk level ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(round(sum by (level) (irate(risk_level_active_total[10s])) ))",
     "legendFormat": "Risk Level Report : {{level}}"
    }
   ]
  },
  {
   "title": "Content Filter ",
   "type": "stat",
   "description": "total number of requests  labeled  by  ruleid  (CF rule)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(irate(requests_triggered_cf_active_total[30s]))",
     "legendFormat": "active"
    },
    {
     "expr": "sum(irate(requests_triggered_cf_report_total[30s]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Reblaze Threat Categories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (tag) (irate(top_tags_reported_total{tag=~\"rtc.*\"}[10s]))) ",
     "legendFormat": "report: {{tag}}"
    },
    {
     "expr": "round(sum by (tag) (irate(top_tags_active_total{tag=~\"rtc.*\"}[10s]))) ",
     "legendFormat": "active:{{tag}}"
    }
   ]
  },
  {
   "title": "Security  Policy Entry  ID",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum by (secpolentryid) (irate(top_secpolentryid_active_total[10s])))",
     "legendFormat": "active:{{secpolentryid}}"
    },
    {
     "expr": "round(sum by (secpolentryid) (irate(top_secpolid_passed_total[10s])))",
     "legendFormat": "passed:{{secpolentryid}}"
    },
    {
     "expr": "round(sum by (secpolentryid) (irate(top_secpolid_reported_total[10s]))) ",
     "legendFormat": "reported:{{secpolentryid}}"
    }
   ]
  },
  {
   "title": "Security  Policy  ID",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum by (secpolid) (irate(top_secpolid_active_total[10s])))",
     "legendFormat": "active:{{secpolid}}"
    },
    {
     "expr": "round(sum by (secpolid) (irate(top_secpolid_passed_total[10s])))",
     "legendFormat": "passed:{{secpolid}}"
    },
    {
     "expr": "round(sum by (secpolid) (irate(top_secpolid_reported_total[10s]))) ",
     "legendFormat": "reported:{{secpolid}}"
    }
   ]
  },
  {
   "title": "Reblaze Signatures (CF)",
   "type": "timeseries",
   "description": "total number of requests  grouped by http status",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ruleid) (irate(top_ruleid_active_total[10s])) ",
     "legendFormat": "{{ruleid}}"
    }
   ]
  },
  {
   "title": "Requests Triggered by Access Control List (ACL)",
   "type": "timeseries",
   "description": "Requests  labeled by ACL",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (aclid) (irate(top_aclid_passed_total[10s])) ",
     "legendFormat": "passed: {{aclid}}"
    }
   ]
  },
  {
   "title": "Requests Triggered by Security Policy Entry ID",
   "type": "timeseries",
   "description": "Requests  grouped by Policy Entry ID name ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (secpolentryid) (irate(top_secpolentryid_passed_total[10s])) ",
     "legendFormat": "passed: {{secpolentryid}}"
    },
    {
     "expr": "sum by (secpolentryid) (irate(top_secpolentryid_reported_total[10s])) ",
     "legendFormat": "report: {{secpolentryid}}"
    },
    {
     "expr": "sum by (secpolentryid) (irate(top_secpolentryid_passed_total[10s])) + sum by (secpolid) (irate(top_secpolentryid_reported_total[10s])) ",
     "legendFormat": "total: {{secpolentryid}}"
    }
   ]
  },
  {
   "title": "Requests Triggered by Security Policy ID",
   "type": "timeseries",
   "description": "Requests  grouped by Policy ID name ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (secpolid) (irate(top_secpolid_passed_total[10s])) ",
     "legendFormat": "passed: {{secpolid}}"
    },
    {
     "expr": "sum by (secpolid) (irate(top_secpolid_reported_total[10s])) ",
     "legendFormat": "report: {{secpolid}}"
    },
    {
     "expr": "(sum by (secpolidntryid) (irate(top_secpolid_passed_total[10s])) )+ (sum by (secpolid) (irate(top_secpolid_reported_total[10s])) )",
     "legendFormat": "total: {{secpolid}}"
    }
   ]
  },
  {
   "title": "Blocked Sections",
   "type": "timeseries",
   "description": "Number of blocked  requests per HTTP requests section  (URI, args, attrs, body, headers )",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(irate(section_active_total[10s]))",
     "legendFormat": "active:{{section}}"
    },
    {
     "expr": "round(irate(section_passed_total[10s])) ",
     "legendFormat": "passed:{{section}}"
    },
    {
     "expr": "round(irate(section_reported_total[10s])) ",
     "legendFormat": "repot:{{section}}"
    }
   ]
  },
  {
   "title": "Maximum Arguments, Cookies, Headers ",
   "type": "timeseries",
   "description": "Number of requests per maximum number of cookies, headers, args.\nShows anomaly for requests with abnormal number cookies, headers, args. ",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (group) (irate(top_max_args_per_request[10s]))) ",
     "legendFormat": "args:{{group}}"
    },
    {
     "expr": "round(sum by (group) (irate(top_max_cookies_per_request[10s]))) ",
     "legendFormat": "cookies:{{group}}"
    },
    {
     "expr": "round(sum by (group) (irate(top_max_headers_per_request[10s]))) ",
     "legendFormat": "headers:{{group}}"
    }
   ]
  }
 ]
}